name: gameroot
description: "Um sistema de vendas de jogos eletrônicos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  
  # Ícones
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3

  # Estados
  provider: ^6.1.2

  # Biometria e reconhecimento facil nativo
  local_auth: ^3.0.1

  # Geolocalização
  geolocator: ^14.0.3

  # Preferências locais
  shared_preferences: ^2.3.0

  # UI
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.1.0
  cached_network_image: ^3.3.1

  # Som da splash screen
  audioplayers: ^6.0.0

  # Formatação e máscaras de campos
  intl: ^0.20.2

  # API IGDB
  http: ^1.2.1

  # Geração de identificadores únicos
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icones/